name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bootstrap workspace
        uses: ./.github/actions/bootstrap
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Run static analysis checks
        run: melos lint
      - name: Build Android APK (profile)
        run: fvm flutter build apk --profile
      - name: Upload APK (profile) artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-profile.apk
          path: build/app/outputs/apk/profile/app-profile.apk
