name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Parse FVM config
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@v2.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: any
          cache: true
      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
      - name: Run static analysis checks
        run: melos lint
      - name: Build Android APK (profile)
        run: flutter build apk --profile
      - name: Upload APK (profile) artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-profile.apk
          path: build/app/outputs/apk/profile/app-profile.apk
